server:
  port: 8080

services:
  list:
    -
     name: Service A
     url: http://18.142.54.177:8080/actuator/health
    -
     name: Service B
     url: http://18.142.54.177:8080/actuator/health
    -
     name: Service C
     url: http://18.142.54.177:8080/actuator/health
    -
     name: Service D
     url: http://18.142.54.177:8080/actuator/health
    -
     name: Service E
     url: http://18.142.54.177:8080/actuator/health

scheduling:
  cron-expression: ${EXPRESSION:*/300 * * * * ?}

notification:
  slack:
    enabled: true 
    token: ${SLACK_TOKEN}